spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/jwt_security
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
server:
  port: 8080
